---

- hosts: loadbalance
  become: true
  pre_tasks:
  - debug:
      msg: "HA proxy address is {{ ansible_all_ipv4_addresses[-1] }} "
  - set_fact:
      _haproxy_backends: "{{ (_haproxy_backends | default([])) + [ __backend ] }}"
    vars:
      __backend:
        name: "{{item}}"
        address: "{{hostvars[item]['ansible_ssh_host']}}:{{hostvars[item]['nodejs_app_port']}}"
    with_items: "{{groups['application'] }}"
    #- "{{groups['application'] | map('extract', hostvars, 'ansible_ssh_host') | list}}"

  - name: install deps
    yum:
      name: libsemanage-python
  - name: Set haproxy_connect_any on flag on and keep it persistent across reboots
    seboolean:
      name: haproxy_connect_any
      state: yes
      persistent: yes
  roles:
  - role: geerlingguy.haproxy
    haproxy_backend_servers: "{{ _haproxy_backends }}"
    haproxy_frontend_name: 'hafrontend'
    haproxy_frontend_bind_address: '{{ ansible_all_ipv4_addresses[-1] }}'
    haproxy_frontend_port: 3000
    haproxy_frontend_mode: 'http'
